/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-05-23 17:46:09 UTC)
 * on 2013-06-01 at 09:51:07 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.monitoring.model;

/**
 * Model definition for Instant.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Instant extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean afterNow;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean beforeNow;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Chronology chronology;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean equalNow;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long millis;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private DateTimeZone zone;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getAfterNow() {
    return afterNow;
  }

  /**
   * @param afterNow afterNow or {@code null} for none
   */
  public Instant setAfterNow(java.lang.Boolean afterNow) {
    this.afterNow = afterNow;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getBeforeNow() {
    return beforeNow;
  }

  /**
   * @param beforeNow beforeNow or {@code null} for none
   */
  public Instant setBeforeNow(java.lang.Boolean beforeNow) {
    this.beforeNow = beforeNow;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Chronology getChronology() {
    return chronology;
  }

  /**
   * @param chronology chronology or {@code null} for none
   */
  public Instant setChronology(Chronology chronology) {
    this.chronology = chronology;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getEqualNow() {
    return equalNow;
  }

  /**
   * @param equalNow equalNow or {@code null} for none
   */
  public Instant setEqualNow(java.lang.Boolean equalNow) {
    this.equalNow = equalNow;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getMillis() {
    return millis;
  }

  /**
   * @param millis millis or {@code null} for none
   */
  public Instant setMillis(java.lang.Long millis) {
    this.millis = millis;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public DateTimeZone getZone() {
    return zone;
  }

  /**
   * @param zone zone or {@code null} for none
   */
  public Instant setZone(DateTimeZone zone) {
    this.zone = zone;
    return this;
  }

  @Override
  public Instant set(String fieldName, Object value) {
    return (Instant) super.set(fieldName, value);
  }

  @Override
  public Instant clone() {
    return (Instant) super.clone();
  }

}
